package management.forms;

import java.awt.Color;
import java.awt.Component;
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringJoiner;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import management.utils.BDConnection;

/**
 * @author Murasov David
 */
public class IssueBookForm extends javax.swing.JFrame {
    private int studentId, bookId, nrBook;
    private boolean isStudentFinded = false, isBookFinded;

    public IssueBookForm() {
        initComponents();
        changeComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/50px-frameIcon.png")));
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.ORANGE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        nrLabel = new javax.swing.JLabel();
        genreBookLabel = new javax.swing.JLabel();
        edituraLabel = new javax.swing.JLabel();
        idBookLabel = new javax.swing.JLabel();
        ISBNLabel = new javax.swing.JLabel();
        denumireField = new javax.swing.JTextField();
        authorsField = new javax.swing.JTextField();
        invalidBookIdLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        Label14 = new javax.swing.JLabel();
        facultyLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genreStudentLabel = new javax.swing.JLabel();
        prenumeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        idStudentLabel = new javax.swing.JLabel();
        invalidStudentIdLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bookIdField = new javax.swing.JTextField();
        Label15 = new javax.swing.JLabel();
        Label17 = new javax.swing.JLabel();
        Label19 = new javax.swing.JLabel();
        Label18 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        issueBtn = new rojerusan.RSMaterialButtonCircle();
        ISBNField = new javax.swing.JTextField();
        Label16 = new javax.swing.JLabel();
        dueDateCalendar = new datechooser.beans.DateChooserCombo();
        issueDateCalendar = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 143));
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 720));

        backLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 153, 0));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left-arrow.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel4.setText("Detalii despre carte");

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Label1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label1.setForeground(java.awt.SystemColor.controlHighlight);
        Label1.setText("Id-ul cărtii:");

        Label2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label2.setForeground(java.awt.SystemColor.controlHighlight);
        Label2.setText("ISBN:");

        Label3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label3.setForeground(java.awt.SystemColor.controlHighlight);
        Label3.setText("Denumirea cărtii:");

        Label4.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label4.setForeground(java.awt.SystemColor.controlHighlight);
        Label4.setText("Numele autorului:");

        Label5.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label5.setForeground(java.awt.SystemColor.controlHighlight);
        Label5.setText("Genul:");

        Label6.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label6.setForeground(java.awt.SystemColor.controlHighlight);
        Label6.setText("Numărul:");

        Label7.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label7.setForeground(java.awt.SystemColor.controlHighlight);
        Label7.setText("Editura:");

        nrLabel.setBackground(new java.awt.Color(255, 255, 255));
        nrLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        nrLabel.setForeground(java.awt.SystemColor.controlHighlight);

        genreBookLabel.setBackground(new java.awt.Color(255, 255, 255));
        genreBookLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        genreBookLabel.setForeground(java.awt.SystemColor.controlHighlight);

        edituraLabel.setBackground(new java.awt.Color(255, 255, 255));
        edituraLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        edituraLabel.setForeground(java.awt.SystemColor.controlHighlight);

        idBookLabel.setBackground(new java.awt.Color(255, 255, 255));
        idBookLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        idBookLabel.setForeground(java.awt.SystemColor.controlHighlight);

        ISBNLabel.setBackground(new java.awt.Color(255, 255, 255));
        ISBNLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        ISBNLabel.setForeground(java.awt.SystemColor.controlHighlight);

        denumireField.setBackground(new java.awt.Color(0, 0, 143));
        denumireField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        denumireField.setForeground(java.awt.SystemColor.controlHighlight);
        denumireField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        denumireField.setToolTipText("");
        denumireField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        denumireField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        denumireField.setPreferredSize(new java.awt.Dimension(0, 30));

        authorsField.setBackground(new java.awt.Color(0, 0, 143));
        authorsField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        authorsField.setForeground(java.awt.SystemColor.controlHighlight);
        authorsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        authorsField.setToolTipText("");
        authorsField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        authorsField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        authorsField.setPreferredSize(new java.awt.Dimension(0, 30));

        invalidBookIdLabel.setBackground(new java.awt.Color(255, 255, 0));
        invalidBookIdLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        invalidBookIdLabel.setForeground(new java.awt.Color(204, 204, 0));
        invalidBookIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label4)
                            .addComponent(Label6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label5)
                            .addComponent(Label2)
                            .addComponent(Label1)
                            .addComponent(Label3)
                            .addComponent(Label7))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nrLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addComponent(genreBookLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idBookLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ISBNLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(denumireField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorsField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(edituraLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(130, 130, 130))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(invalidBookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Label1)
                                    .addComponent(idBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(Label2))
                            .addComponent(ISBNLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label3)
                            .addComponent(denumireField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(Label4))
                    .addComponent(authorsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genreBookLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label6)
                    .addComponent(nrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label7)
                    .addComponent(edituraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(invalidBookIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel4.setBackground(new java.awt.Color(122, 0, 0));
        jPanel4.setForeground(java.awt.SystemColor.controlHighlight);
        jPanel4.setPreferredSize(new java.awt.Dimension(580, 720));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel3.setText("Detalii despre student");

        jPanel3.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel3.setMinimumSize(new java.awt.Dimension(100, 3));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        Label8.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label8.setForeground(java.awt.SystemColor.controlHighlight);
        Label8.setText("Id-ul studentului:");

        Label9.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label9.setForeground(java.awt.SystemColor.controlHighlight);
        Label9.setText("Numele studentului:");

        Label10.setFont(new java.awt.Font("Comic Sans MS", 0, 19)); // NOI18N
        Label10.setForeground(java.awt.SystemColor.controlHighlight);
        Label10.setText("Prenumele studentului:");

        Label11.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label11.setForeground(java.awt.SystemColor.controlHighlight);
        Label11.setText("Genul:");

        Label12.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label12.setForeground(java.awt.SystemColor.controlHighlight);
        Label12.setText("E-mail:");

        Label13.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label13.setForeground(java.awt.SystemColor.controlHighlight);
        Label13.setText("Grupa:");

        Label14.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label14.setForeground(java.awt.SystemColor.controlHighlight);
        Label14.setText("Facultatea:");

        facultyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        facultyLabel.setForeground(java.awt.SystemColor.controlHighlight);

        groupLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        groupLabel.setForeground(java.awt.SystemColor.controlHighlight);

        emailLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        emailLabel.setForeground(java.awt.SystemColor.controlHighlight);

        genreStudentLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        genreStudentLabel.setForeground(java.awt.SystemColor.controlHighlight);

        prenumeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 19)); // NOI18N
        prenumeLabel.setForeground(java.awt.SystemColor.controlHighlight);

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        nameLabel.setForeground(java.awt.SystemColor.controlHighlight);

        idStudentLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        idStudentLabel.setForeground(java.awt.SystemColor.controlHighlight);

        invalidStudentIdLabel.setBackground(new java.awt.Color(255, 255, 0));
        invalidStudentIdLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        invalidStudentIdLabel.setForeground(new java.awt.Color(204, 204, 0));
        invalidStudentIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label11)
                                    .addComponent(Label13)
                                    .addComponent(Label12)
                                    .addComponent(Label14)
                                    .addComponent(Label8)
                                    .addComponent(Label10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(groupLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(genreStudentLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prenumeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(facultyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(invalidStudentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label8)
                    .addComponent(idStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label9)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label10)
                    .addComponent(prenumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genreStudentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label12))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Label13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(groupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label14)
                    .addComponent(facultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(invalidStudentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 77));
        jPanel5.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Oferă carte");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(194, 194, 194)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);

        bookIdField.setBackground(new java.awt.Color(122, 0, 0));
        bookIdField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookIdField.setForeground(java.awt.SystemColor.controlHighlight);
        bookIdField.setToolTipText("");
        bookIdField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookIdField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        bookIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                bookIdFieldFocusLost(evt);
            }
        });

        Label15.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label15.setText("Id-ul cărtii:");

        Label17.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label17.setText("Id-ul studentului:");

        Label19.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label19.setText("Termenul:");

        Label18.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label18.setText("Data oferirii:");

        studentIdField.setBackground(new java.awt.Color(122, 0, 0));
        studentIdField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentIdField.setForeground(java.awt.SystemColor.controlHighlight);
        studentIdField.setToolTipText("");
        studentIdField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentIdField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        studentIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIdFieldFocusLost(evt);
            }
        });

        issueBtn.setBackground(new java.awt.Color(122, 0, 0));
        issueBtn.setText("Oferă carte");
        issueBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });

        ISBNField.setBackground(new java.awt.Color(122, 0, 0));
        ISBNField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ISBNField.setForeground(java.awt.SystemColor.controlHighlight);
        ISBNField.setToolTipText("");
        ISBNField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        ISBNField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        ISBNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ISBNFieldFocusLost(evt);
            }
        });

        Label16.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label16.setText("ISBN al cărtii:");

        dueDateCalendar.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dueDateCalendar.setLocale(new java.util.Locale("ro", "", ""));
    dueDateCalendar.setCalendarPreferredSize(new java.awt.Dimension(320, 180));
    dueDateCalendar.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
    dueDateCalendar.setCalendarBackground(new java.awt.Color(153, 0, 0));
    dueDateCalendar.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
    dueDateCalendar.setNavigateFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));

    issueDateCalendar.setCurrentView(new datechooser.view.appearance.AppearancesList("Grey",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
issueDateCalendar.setLocale(new java.util.Locale("ro", "", ""));
issueDateCalendar.setCalendarPreferredSize(new java.awt.Dimension(320, 180));
issueDateCalendar.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
issueDateCalendar.setCalendarBackground(new java.awt.Color(153, 0, 0));
issueDateCalendar.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
issueDateCalendar.setNavigateFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));

javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
jPanel6.setLayout(jPanel6Layout);
jPanel6Layout.setHorizontalGroup(
    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(jPanel6Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 246, Short.MAX_VALUE)
                .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label17)
                    .addComponent(Label19)
                    .addComponent(Label18)
                    .addComponent(Label16)
                    .addComponent(Label15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ISBNField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addComponent(studentIdField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bookIdField))
                    .addComponent(dueDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))))
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(Label15)
                .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(53, 53, 53)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(Label16)
                .addComponent(ISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(58, 58, 58)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Label17, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(studentIdField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(62, 62, 62)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Label18)
                .addComponent(issueDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(54, 54, 54)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(Label19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                    .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16))
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(dueDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        redirectTo(new MainPage());
    }//GEN-LAST:event_backLabelMouseClicked

     private void redirectTo(JFrame frame){
        frame.setVisible(true);
        dispose();
    }
    
    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        if(this.isBookFinded == false){
            JOptionPane.showMessageDialog(this, "Cartea nu a fost găsită!");
            return;
        }else if(this.isStudentFinded == false){
            JOptionPane.showMessageDialog(this, "Studentul nu a fost găsit!");
            return;
        }
        
        if(nrBook == 0){
            JOptionPane.showMessageDialog(this, "Cartea nu este disponibila");
            return;
        }
            
        if(isAlreadyUsed() == true){
            JOptionPane.showMessageDialog(this, "Acest student deja are aceasta carte.");
        }else{
            if(issueBook() == true){
                JOptionPane.showMessageDialog(this, "Cartea a fost oferită pentru student.");
                updateNrBooks(-1);
            }else{
                JOptionPane.showMessageDialog(this, "Nu se poate oferi cartea.");
            }
        }
    }//GEN-LAST:event_issueBtnActionPerformed

    public void setBookId(int bookId){
        this.bookId = bookId;
    }
    
    public void setStudentId(int studentId){
        this.studentId = studentId;
    }
    
    public void setNrBook(int nrBook){
        this.nrBook = nrBook;
    }
    
    private void updateNrBooks(int number){
        int rowCount, nrAfter;
        nrAfter = Integer.parseInt(nrLabel.getText()) + number;
        setNrBook(nrAfter);
        
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("UPDATE carti SET nr_carti = ? WHERE id_carte = ?");
            prepst.setInt(1, nrAfter);
            prepst.setInt(2, this.bookId);
            
            rowCount = prepst.executeUpdate();
            
            if(rowCount > 0){
                nrLabel.setText(Integer.toString(nrAfter));
            }else{
                JOptionPane.showMessageDialog(this, "Eroare de scadere a numărului de cărti!");
            }   
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    
    public void setInfoBookById(){
        StringJoiner str_authors = new StringJoiner(", ");
        int bookId, nrBook;
        bookId = Integer.parseInt(bookIdField.getText());
        
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepstBooks = connection.prepareStatement("SELECT c.id_carte, c.ISBN, c.denumire_carte, g.denumire_gen, c.editor, c.nr_carti "
                    + "FROM carti c INNER JOIN genuri g USING(id_gen) WHERE c.id_carte = ?");
            PreparedStatement prepstAuthors = connection.prepareStatement("SELECT CONCAT(a.nume_autor, ' ', a.prenume_autor) as autor "
                    + "FROM carti c INNER JOIN autorii_cartilor ac ON c.id_carte = ac.id_carte "
                    + "INNER JOIN autori a ON a.id_autor = ac.id_autor WHERE ac.id_carte = ?");
            
            prepstBooks.setInt(1, bookId);
            ResultSet rsBooks = prepstBooks.executeQuery();
            
            if(rsBooks.next()){
                nrBook = Integer.parseInt(rsBooks.getString("nr_carti"));
                bookId = Integer.parseInt(rsBooks.getString("id_carte"));
  
                idBookLabel.setText(Integer.toString(bookId));
                ISBNLabel.setText(rsBooks.getString("ISBN"));
                denumireField.setText(rsBooks.getString("denumire_carte"));
                genreBookLabel.setText(rsBooks.getString("denumire_gen"));
                edituraLabel.setText(rsBooks.getString("editor"));
                nrLabel.setText(Integer.toString(nrBook));
                
                setBookId(bookId);
                setNrBook(nrBook);
                
                prepstAuthors.setInt(1, bookId);
                ResultSet rsAuthors = prepstAuthors.executeQuery();
                while(rsAuthors.next()){
                    str_authors.add(rsAuthors.getString("autor"));
                    invalidBookIdLabel.setText("");
                    this.isBookFinded = true;
                }
                authorsField.setText(str_authors.toString());
            }else{
                invalidBookIdLabel.setText("Id-ul cărtii nu există");
                this.isBookFinded = false;
            } 
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    
    public void setInfoBookByISBN(){
        StringJoiner str_authors = new StringJoiner(", ");
        String ISBN = ISBNField.getText();
        int bookId, nrBook;
        
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepstBooks = connection.prepareStatement("SELECT c.id_carte, c.ISBN, c.denumire_carte, g.denumire_gen, c.editor, c.nr_carti "
                    + "FROM carti c INNER JOIN genuri g USING(id_gen) WHERE c.ISBN = ?");
            PreparedStatement prepstAuthors = connection.prepareStatement("SELECT CONCAT(a.nume_autor, ' ', a.prenume_autor) as autor "
                    + "FROM carti c INNER JOIN autorii_cartilor ac ON c.id_carte = ac.id_carte "
                    + "INNER JOIN autori a ON a.id_autor = ac.id_autor WHERE c.ISBN = ?");
            
            prepstBooks.setString(1, ISBN);
            ResultSet rsBooks = prepstBooks.executeQuery();
            
            if(rsBooks.next()){
                nrBook = Integer.parseInt(rsBooks.getString("nr_carti"));
                bookId = Integer.parseInt(rsBooks.getString("id_carte"));
                
                idBookLabel.setText(Integer.toString(bookId));
                ISBNLabel.setText(rsBooks.getString("ISBN"));
                denumireField.setText(rsBooks.getString("denumire_carte"));
                genreBookLabel.setText(rsBooks.getString("denumire_gen"));
                edituraLabel.setText(rsBooks.getString("editor"));
                nrLabel.setText(Integer.toString(nrBook));
                bookIdField.setText(Integer.toString(bookId));
                
                setBookId(bookId);
                setNrBook(nrBook);
                
                prepstAuthors.setString(1, ISBN);
                ResultSet rsAuthors = prepstAuthors.executeQuery();
                if(rsAuthors.next()){
                    str_authors.add(rsAuthors.getString("autor"));
                    authorsField.setText(str_authors.toString());
                    invalidBookIdLabel.setText("");
                    this.isBookFinded = true;
                }else{
                    invalidBookIdLabel.setText("ISBN al cărtii nu există");
                    this.isBookFinded = false;
                } 
            }else{
                invalidBookIdLabel.setText("ISBN al cărtii nu există");
                this.isBookFinded = false;
            } 
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    
    public void setInfoStudent(){
        int studentId = Integer.parseInt(studentIdField.getText());
        
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepstStudent = connection.prepareStatement("SELECT * FROM studenti INNER JOIN facultati USING(id_facultate) WHERE id_studentului = ?");
            prepstStudent.setInt(1, studentId);
            ResultSet rs = prepstStudent.executeQuery();
            if(rs.next()){
                idStudentLabel.setText(rs.getString("id_studentului"));
                nameLabel.setText(rs.getString("numele"));
                prenumeLabel.setText(rs.getString("prenumele"));
                emailLabel.setText(rs.getString("email"));
                groupLabel.setText(rs.getString("grupa"));
                facultyLabel.setText(rs.getString("numele_facultate"));
                genreStudentLabel.setText(rs.getString("genul"));
                invalidStudentIdLabel.setText("");
                this.isStudentFinded = true;
                setStudentId(studentId);
            }else{
                invalidStudentIdLabel.setText("Id-ul studentului nu există!");
                this.isStudentFinded = false;
            }       
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public boolean issueBook(){
        SimpleDateFormat smp = new SimpleDateFormat("yyyy-MM-dd");
        Long l1, l2;
        int rowCount;
        String date1, date2; 
        Date issueDate = null, dueDate = null;
       
        date1 = smp.format(issueDateCalendar.getSelectedDate().getTime());
        date2 = smp.format(dueDateCalendar.getSelectedDate().getTime());
        
        try{
            issueDate = smp.parse(date1);
            dueDate = smp.parse(date2);
        }catch(ParseException ex){
            ex.printStackTrace();
        }
        
        l1 = issueDate.getTime();
        l2 = dueDate.getTime();
        
        java.sql.Date sqlIssueDate = new java.sql.Date(l1);
        java.sql.Date sqlDueDate = new java.sql.Date(l2);
        
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("INSERT INTO carti_oferite VALUES(?, ?, ?, ?, ?)");
            prepst.setInt(1, this.bookId);
            prepst.setInt(2, this.studentId);
            prepst.setDate(3, sqlIssueDate);
            prepst.setDate(4, sqlDueDate);
            prepst.setString(5, "In asteptare");
            
            rowCount = prepst.executeUpdate();
            if(rowCount > 0){
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return false;
    }
    
    private boolean isAlreadyUsed(){
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("SELECT * FROM carti_oferite WHERE id_carte = ? "
                    + "AND id_studentului = ? AND status = 'In asteptare'");
            prepst.setInt(1, bookId);
            prepst.setInt(2, studentId);
            
            ResultSet rs = prepst.executeQuery();
            if(rs.next()){
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return false;
    }
    
    private void bookIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bookIdFieldFocusLost
        if(!bookIdField.getText().equals("")){
            setInfoBookById();
        }
    }//GEN-LAST:event_bookIdFieldFocusLost

    private void ISBNFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ISBNFieldFocusLost
        if(!ISBNField.getText().equals("")){
            setInfoBookByISBN();
        }
    }//GEN-LAST:event_ISBNFieldFocusLost

    private void studentIdFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIdFieldFocusLost
        if(!studentIdField.getText().equals("")){
            setInfoStudent();
        }
    }//GEN-LAST:event_studentIdFieldFocusLost


    
    private void changeComponents(){
        denumireField.setMargin(new Insets(0, 0, 0, 0));
        authorsField.setMargin(new Insets(0, 0, 0, 0));
        Border empty = new EmptyBorder(0, 0, 0, 0);
        denumireField.setBorder(empty);
        authorsField.setBorder(empty);
        
        authorsField.setEditable(false);
        denumireField.setEditable(false);
        
        for(Component c : dueDateCalendar.getComponents()){
            ((JComponent)c).setBackground(new Color(153, 0, 0)); 
            ((JComponent)c).setForeground(Color.WHITE);
        }
        for(Component c : issueDateCalendar.getComponents()){
            ((JComponent)c).setBackground(new Color(153, 0, 0)); 
            ((JComponent)c).setForeground(Color.WHITE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNField;
    private javax.swing.JLabel ISBNLabel;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label17;
    private javax.swing.JLabel Label18;
    private javax.swing.JLabel Label19;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JTextField authorsField;
    private javax.swing.JLabel backLabel;
    private javax.swing.JTextField bookIdField;
    private javax.swing.JTextField denumireField;
    private datechooser.beans.DateChooserCombo dueDateCalendar;
    private javax.swing.JLabel edituraLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel facultyLabel;
    private javax.swing.JLabel genreBookLabel;
    private javax.swing.JLabel genreStudentLabel;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel idBookLabel;
    private javax.swing.JLabel idStudentLabel;
    private javax.swing.JLabel invalidBookIdLabel;
    private javax.swing.JLabel invalidStudentIdLabel;
    private rojerusan.RSMaterialButtonCircle issueBtn;
    private datechooser.beans.DateChooserCombo issueDateCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nrLabel;
    private javax.swing.JLabel prenumeLabel;
    private javax.swing.JTextField studentIdField;
    // End of variables declaration//GEN-END:variables
}
