package management.forms;

import management.forms.ManagementOfBooks;
import management.forms.ManagementOfStudents;
import management.forms.ReturnBookForm;
import management.forms.SignInForm;
import management.forms.ViewDebtors;
import management.forms.ViewRecords;
import java.awt.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringJoiner;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import management.utils.BDConnection;
import static javax.swing.text.StyleConstants.Bold;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author User
 */
public class MainPage extends javax.swing.JFrame {
    private final Color mouseEnterColor = Color.BLACK;
    private final Color mouseExitColor = Color.WHITE;
    private DefaultTableModel tableModelOfStudents, tableModelOfBooks;
    
    public MainPage() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/50px-frameIcon.png")));
        
        setInfoOfQuantity();
        setTableModelOfStudents();
        setTableModelOfBooks();
        displayBooksOnPieChart();
    }
    
    private void displayBooksOnPieChart(){
        DefaultPieDataset barDataset = new DefaultPieDataset();
        JFreeChart piechart;
        
        try(Connection connection = BDConnection.getConnection()){
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("SELECT c.denumire_carte, COUNT(*) as count "
                    + "FROM carti_oferite cf INNER JOIN carti c ON cf.id_carte = c.id_carte group by c.id_carte");
 
            while(rs.next()){
                barDataset.setValue(rs.getString("denumire_carte"), new Double(rs.getDouble("count")));   
            }
        }catch (SQLException ex){
            ex.printStackTrace();
        }

        piechart = ChartFactory.createPieChart("Statistica despre cărtile emise", barDataset, false, true, false);
        piechart.getTitle().setPaint(new Color(255,255,255));
        piechart.getTitle().setFont(new Font("Comic Sans MS", Font.BOLD, 24));
        piechart.setBackgroundPaint(new Color(51,51,51));
        
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
        piePlot.setBackgroundPaint(Color.GRAY);
        
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelPie.removeAll();
        panelPie.add(barChartPanel, BorderLayout.CENTER);
        panelPie.validate();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        nrOfStudentsLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nrOfIssuedBooksLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nrOfBooksLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOfStudents = new rojerusan.RSTableMetro();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOfBooks = new rojerusan.RSTableMetro();
        panelPie = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        nrOfDebtorsLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manageAuthorsLabel = new javax.swing.JLabel();
        returnLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        issueBookLabel = new javax.swing.JLabel();
        studentManageLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logoutLabel = new javax.swing.JLabel();
        bookManageLabel = new javax.swing.JLabel();
        viewRegLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        manageGenresLabel = new javax.swing.JLabel();
        viewDeptorsLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        manageFacultiesLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Librarytitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlHighlight);

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1050));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nr. de studenti");

        nrOfStudentsLabel.setBackground(new java.awt.Color(153, 0, 0));
        nrOfStudentsLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nrOfStudentsLabel.setForeground(java.awt.SystemColor.controlHighlight);
        nrOfStudentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nrOfStudentsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_People_50px.png"))); // NOI18N
        nrOfStudentsLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(nrOfStudentsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrOfStudentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        nrOfIssuedBooksLabel.setBackground(new java.awt.Color(0, 0, 153));
        nrOfIssuedBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nrOfIssuedBooksLabel.setForeground(java.awt.SystemColor.controlHighlight);
        nrOfIssuedBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nrOfIssuedBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Sell_50px.png"))); // NOI18N
        nrOfIssuedBooksLabel.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Nr. de cărti oferite");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(nrOfIssuedBooksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrOfIssuedBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 102)));
        jPanel8.setAlignmentX(0.0F);
        jPanel8.setAlignmentY(0.0F);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nr. de cărti");

        nrOfBooksLabel.setBackground(new java.awt.Color(0, 0, 153));
        nrOfBooksLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nrOfBooksLabel.setForeground(java.awt.SystemColor.controlHighlight);
        nrOfBooksLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nrOfBooksLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Book_Shelf_50px.png"))); // NOI18N
        nrOfBooksLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
            .addComponent(nrOfBooksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrOfBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableOfStudents.setBackground(new java.awt.Color(102, 102, 102));
        tableOfStudents.setForeground(java.awt.SystemColor.controlHighlight);
        tableOfStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nume", "Prenume", "Email", "Grupa", "Facultatea", "Genul"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableOfStudents.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tableOfStudents.setColorFilasBackgound1(new java.awt.Color(153, 0, 0));
        tableOfStudents.setColorFilasBackgound2(new java.awt.Color(153, 0, 0));
        tableOfStudents.setColorFilasForeground1(java.awt.SystemColor.controlHighlight);
        tableOfStudents.setColorFilasForeground2(java.awt.SystemColor.controlHighlight);
        tableOfStudents.setFuenteFilas(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tableOfStudents.setFuenteHead(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tableOfStudents.setRowHeight(35);
        jScrollPane2.setViewportView(tableOfStudents);
        if (tableOfStudents.getColumnModel().getColumnCount() > 0) {
            tableOfStudents.getColumnModel().getColumn(0).setPreferredWidth(3);
        }

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setText("Detalii despre studenti");

        tableOfBooks.setBackground(new java.awt.Color(102, 102, 102));
        tableOfBooks.setForeground(java.awt.SystemColor.controlHighlight);
        tableOfBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "ISBN", "Denumire", "Autor", "Genul", "Editura", "Nr"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableOfBooks.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tableOfBooks.setColorFilasBackgound1(new java.awt.Color(153, 0, 0));
        tableOfBooks.setColorFilasBackgound2(new java.awt.Color(153, 0, 0));
        tableOfBooks.setColorFilasForeground1(java.awt.SystemColor.controlHighlight);
        tableOfBooks.setColorFilasForeground2(java.awt.SystemColor.controlHighlight);
        tableOfBooks.setFuenteFilas(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        tableOfBooks.setFuenteHead(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tableOfBooks.setRowHeight(35);
        jScrollPane3.setViewportView(tableOfBooks);
        if (tableOfBooks.getColumnModel().getColumnCount() > 0) {
            tableOfBooks.getColumnModel().getColumn(0).setPreferredWidth(3);
            tableOfBooks.getColumnModel().getColumn(2).setPreferredWidth(140);
            tableOfBooks.getColumnModel().getColumn(3).setPreferredWidth(120);
            tableOfBooks.getColumnModel().getColumn(4).setPreferredWidth(80);
            tableOfBooks.getColumnModel().getColumn(5).setPreferredWidth(100);
            tableOfBooks.getColumnModel().getColumn(6).setPreferredWidth(5);
        }

        panelPie.setBackground(new java.awt.Color(102, 102, 102));
        panelPie.setForeground(new java.awt.Color(255, 255, 255));
        panelPie.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        panelPie.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setText("Detalii despre cărti");

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        nrOfDebtorsLabel.setBackground(new java.awt.Color(204, 102, 0));
        nrOfDebtorsLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        nrOfDebtorsLabel.setForeground(java.awt.SystemColor.controlHighlight);
        nrOfDebtorsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nrOfDebtorsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        nrOfDebtorsLabel.setOpaque(true);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel20.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Nr. de datornici");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(nrOfDebtorsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrOfDebtorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelPie, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(panelPie, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));

        jLabel3.setBackground(java.awt.SystemColor.controlHighlight);
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel3.setText("Home");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Cărti:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Circulatie:");

        manageAuthorsLabel.setBackground(java.awt.SystemColor.controlHighlight);
        manageAuthorsLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        manageAuthorsLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageAuthorsLabel.setText("Gestionarea autorilor");
        manageAuthorsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageAuthorsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageAuthorsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageAuthorsLabelMouseExited(evt);
            }
        });

        returnLabel.setBackground(java.awt.SystemColor.controlHighlight);
        returnLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        returnLabel.setForeground(new java.awt.Color(255, 255, 255));
        returnLabel.setText("Returnează cartea");
        returnLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnLabelMouseExited(evt);
            }
        });

        jLabel7.setBackground(java.awt.SystemColor.controlHighlight);
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("|");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("Genuri:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("Studenti:");

        issueBookLabel.setBackground(java.awt.SystemColor.controlHighlight);
        issueBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        issueBookLabel.setForeground(new java.awt.Color(255, 255, 255));
        issueBookLabel.setText("Oferă cartea");
        issueBookLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBookLabelMouseExited(evt);
            }
        });

        studentManageLabel.setBackground(java.awt.SystemColor.controlHighlight);
        studentManageLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        studentManageLabel.setForeground(new java.awt.Color(255, 255, 255));
        studentManageLabel.setText("Gestionarea studentilor");
        studentManageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentManageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentManageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentManageLabelMouseExited(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));

        logoutLabel.setBackground(java.awt.SystemColor.controlHighlight);
        logoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        logoutLabel.setForeground(java.awt.SystemColor.controlHighlight);
        logoutLabel.setText("Log Out");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(logoutLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        bookManageLabel.setBackground(java.awt.SystemColor.controlHighlight);
        bookManageLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        bookManageLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookManageLabel.setText("Gestionarea cărtilor");
        bookManageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookManageLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookManageLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookManageLabelMouseExited(evt);
            }
        });

        viewRegLabel.setBackground(java.awt.SystemColor.controlHighlight);
        viewRegLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        viewRegLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewRegLabel.setText("Vizualizarea înregistrărilor");
        viewRegLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRegLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewRegLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewRegLabelMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Vizualizări:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 153));
        jLabel17.setText("Autori:");

        manageGenresLabel.setBackground(java.awt.SystemColor.controlHighlight);
        manageGenresLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        manageGenresLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageGenresLabel.setText("Gestionarea genurilor");
        manageGenresLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageGenresLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageGenresLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageGenresLabelMouseExited(evt);
            }
        });

        viewDeptorsLabel.setBackground(java.awt.SystemColor.controlHighlight);
        viewDeptorsLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        viewDeptorsLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewDeptorsLabel.setText("Vizualizarea celor datornici");
        viewDeptorsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDeptorsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewDeptorsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewDeptorsLabelMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("Facultăti:");

        manageFacultiesLabel.setBackground(java.awt.SystemColor.controlHighlight);
        manageFacultiesLabel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        manageFacultiesLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageFacultiesLabel.setText("Gestionarea facultătilor");
        manageFacultiesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageFacultiesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageFacultiesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageFacultiesLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(issueBookLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnLabel)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(studentManageLabel)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(bookManageLabel)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewDeptorsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewRegLabel))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(manageGenresLabel)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(manageAuthorsLabel)
                                            .addGap(8, 8, 8)))
                                    .addGap(10, 10, 10))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46))
                                .addComponent(manageFacultiesLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(58, 58, 58))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageAuthorsLabel)
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageGenresLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageFacultiesLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookManageLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentManageLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewRegLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDeptorsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnLabel)
                    .addComponent(issueBookLabel)
                    .addComponent(jLabel7))
                .addGap(70, 70, 70)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 104));

        Librarytitle.setFont(new java.awt.Font("Comic Sans MS", 1, 44)); // NOI18N
        Librarytitle.setForeground(new java.awt.Color(255, 153, 0));
        Librarytitle.setText("Bibliotecă");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin-icon2.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Admin");

        mainIconLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mainIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mainPageIcon.png"))); // NOI18N
        mainIconLabel.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainIconLabel)
                .addGap(29, 29, 29)
                .addComponent(Librarytitle, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainIconLabel)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Librarytitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1555, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1932, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 975, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookManageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookManageLabelMouseClicked
        redirectTo(new ManagementOfBooks());
    }//GEN-LAST:event_bookManageLabelMouseClicked

    private void studentManageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentManageLabelMouseEntered
        studentManageLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_studentManageLabelMouseEntered

    private void studentManageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentManageLabelMouseClicked
        redirectTo(new ManagementOfStudents());
    }//GEN-LAST:event_studentManageLabelMouseClicked

    public final void setInfoOfQuantity(){
        Date date = new Date((long)System.currentTimeMillis());
        String sqlBooks, sqlStudents, sqlDebtors, sqlIssuedBooks;
        
        sqlBooks = "SELECT COUNT(*) as num FROM carti";
        sqlStudents = "SELECT COUNT(*) as num FROM studenti";
        sqlIssuedBooks = "SELECT COUNT(*) as num FROM carti_oferite WHERE status = 'In asteptare'";
        sqlDebtors = "SELECT COUNT(*) as num FROM carti_oferite WHERE data_oferirii < ? AND status = 'In asteptare'";
        
        try(Connection connection = BDConnection.getConnection()){
            Statement st = connection.createStatement();
            
            setTextNumToLabel(st, nrOfBooksLabel, sqlBooks);
            setTextNumToLabel(st, nrOfStudentsLabel, sqlStudents);
            setTextNumToLabel(st, nrOfIssuedBooksLabel, sqlIssuedBooks);
            
            PreparedStatement prepst = connection.prepareStatement(sqlDebtors);
            prepst.setDate(1, date);
            setTextNumToLabel(prepst, nrOfDebtorsLabel);   
        }catch (SQLException ex){
            ex.printStackTrace();
        }
    }
    
    private void setTextNumToLabel(Statement st, javax.swing.JLabel label, String sql) throws SQLException{ 
        ResultSet rs = st.executeQuery(sql);
        if(rs.next()){
            label.setText(rs.getString("num"));
        }
    }
    
    private void setTextNumToLabel(PreparedStatement prepst, javax.swing.JLabel label) throws SQLException{ 
        ResultSet rs = prepst.executeQuery();
        if(rs.next()){
            label.setText(rs.getString("num"));
        }
    }
    
    
    private void manageGenresLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageGenresLabelMouseExited
        manageGenresLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_manageGenresLabelMouseExited

    private void bookManageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookManageLabelMouseExited
        bookManageLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_bookManageLabelMouseExited

    private void bookManageLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookManageLabelMouseEntered
        bookManageLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_bookManageLabelMouseEntered

    private void studentManageLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentManageLabelMouseExited
       studentManageLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_studentManageLabelMouseExited

    private void issueBookLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseClicked
        redirectTo(new IssueBookForm());
    }//GEN-LAST:event_issueBookLabelMouseClicked

    private void issueBookLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseEntered
        issueBookLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_issueBookLabelMouseEntered

    private void issueBookLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBookLabelMouseExited
        issueBookLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_issueBookLabelMouseExited

    private void viewRegLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRegLabelMouseClicked
        redirectTo(new ViewRecords());
    }//GEN-LAST:event_viewRegLabelMouseClicked

    private void viewRegLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRegLabelMouseEntered
        viewRegLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_viewRegLabelMouseEntered

    private void viewRegLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRegLabelMouseExited
        viewRegLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_viewRegLabelMouseExited

    private void viewDeptorsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDeptorsLabelMouseClicked
        redirectTo(new ViewDebtors());
    }//GEN-LAST:event_viewDeptorsLabelMouseClicked

    private void viewDeptorsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDeptorsLabelMouseEntered
        viewDeptorsLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_viewDeptorsLabelMouseEntered

    private void viewDeptorsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDeptorsLabelMouseExited
        viewDeptorsLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_viewDeptorsLabelMouseExited

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        redirectTo(new SignInForm());
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void logoutLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        logoutLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        logoutLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_logoutLabelMouseExited

    private void returnLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLabelMouseClicked
        redirectTo(new ReturnBookForm());
    }//GEN-LAST:event_returnLabelMouseClicked

    private void returnLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLabelMouseEntered
        returnLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_returnLabelMouseEntered

    private void returnLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnLabelMouseExited
        returnLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_returnLabelMouseExited

    private void manageGenresLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageGenresLabelMouseEntered
        manageGenresLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_manageGenresLabelMouseEntered

    private void manageGenresLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageGenresLabelMouseClicked
        redirectTo(new ManagementOfGenres());
    }//GEN-LAST:event_manageGenresLabelMouseClicked

    private void manageAuthorsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAuthorsLabelMouseClicked
        redirectTo(new ManagementOfAuthors());
    }//GEN-LAST:event_manageAuthorsLabelMouseClicked

    private void manageAuthorsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAuthorsLabelMouseEntered
        manageAuthorsLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_manageAuthorsLabelMouseEntered

    private void manageAuthorsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAuthorsLabelMouseExited
        manageAuthorsLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_manageAuthorsLabelMouseExited

    private void manageFacultiesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageFacultiesLabelMouseClicked
        redirectTo(new ManagementOfFaculties());
    }//GEN-LAST:event_manageFacultiesLabelMouseClicked

    private void manageFacultiesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageFacultiesLabelMouseEntered
        manageFacultiesLabel.setForeground(mouseEnterColor);
    }//GEN-LAST:event_manageFacultiesLabelMouseEntered

    private void manageFacultiesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageFacultiesLabelMouseExited
        manageFacultiesLabel.setForeground(mouseExitColor);
    }//GEN-LAST:event_manageFacultiesLabelMouseExited

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    
    private void setTableModelOfStudents(){
        StringJoiner str_authors = new StringJoiner(", ");
        
        try(Connection connection = BDConnection.getConnection()){
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM studenti s INNER JOIN facultati f USING(id_facultate)");
            while(rs.next()){
                int studentId = rs.getInt("id_studentului");
                String firstName = rs.getString("numele");
                String lastName = rs.getString("prenumele");
                String email = rs.getString("email");
                String group = rs.getString("grupa");
                String faculty = rs.getString("numele_facultate");
                String genre = rs.getString("genul");

                Object[] obj = {studentId, firstName, lastName, email, group, faculty, genre};
                
                tableModelOfStudents = (DefaultTableModel)tableOfStudents.getModel();
                tableModelOfStudents.addRow(obj);
            }      
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void setTableModelOfBooks(){
        StringJoiner str_authors = new StringJoiner(", ");
        
        try(Connection connection = BDConnection.getConnection()){
            Statement st1 = connection.createStatement();
            ResultSet rsBooks = st1.executeQuery("SELECT c.id_carte, c.ISBN, c.denumire_carte, g.denumire_gen, c.editor, c.nr_carti "
                    + "FROM carti c INNER JOIN genuri g USING(id_gen)");
            PreparedStatement prepstAuthors = connection.prepareStatement("SELECT CONCAT(a.nume_autor, ' ', a.prenume_autor) as autor "
                    + "FROM carti c INNER JOIN autorii_cartilor ac ON c.id_carte = ac.id_carte "
                    + "INNER JOIN autori a ON a.id_autor = ac.id_autor WHERE ac.id_carte = ?");
            while(rsBooks.next()){
                int book_id = rsBooks.getInt("id_carte");
                String ISBN = rsBooks.getString("ISBN");
                String book_name = rsBooks.getString("denumire_carte");
                String gen = rsBooks.getString("denumire_gen");
                String editura = rsBooks.getString("editor");
                int nr_carti = rsBooks.getInt("nr_carti");
                
                prepstAuthors.setInt(1, book_id);
                ResultSet rsAuthors = prepstAuthors.executeQuery();
                while(rsAuthors.next()){
                    str_authors.add(rsAuthors.getString("autor"));
                }

                Object[] obj = {book_id, ISBN, book_name, str_authors, gen, editura, nr_carti};
                
                tableModelOfBooks = (DefaultTableModel)tableOfBooks.getModel();
                tableModelOfBooks.addRow(obj);
                
                str_authors = new StringJoiner(", ");
            }   
           
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    public void clearTableOfStudents(){
        tableModelOfStudents.setRowCount(0);
    }
    
    public void clearTableOfBooks(){
        tableModelOfBooks.setRowCount(0);
    }
    
    private void redirectTo(JFrame frame){
        frame.setVisible(true);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Librarytitle;
    private javax.swing.JLabel bookManageLabel;
    private javax.swing.JLabel issueBookLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JLabel mainIconLabel;
    private javax.swing.JLabel manageAuthorsLabel;
    private javax.swing.JLabel manageFacultiesLabel;
    private javax.swing.JLabel manageGenresLabel;
    private javax.swing.JLabel nrOfBooksLabel;
    private javax.swing.JLabel nrOfDebtorsLabel;
    private javax.swing.JLabel nrOfIssuedBooksLabel;
    private javax.swing.JLabel nrOfStudentsLabel;
    private javax.swing.JPanel panelPie;
    private javax.swing.JLabel returnLabel;
    private javax.swing.JLabel studentManageLabel;
    private rojerusan.RSTableMetro tableOfBooks;
    private rojerusan.RSTableMetro tableOfStudents;
    private javax.swing.JLabel viewDeptorsLabel;
    private javax.swing.JLabel viewRegLabel;
    // End of variables declaration//GEN-END:variables


}
