package management.forms;

import java.awt.Color;
import java.awt.Insets;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.Date;
import java.util.StringJoiner;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import management.elements.Manages;
import management.forms.infoCards.BookInfoCard;
import management.forms.infoCards.StudentInfoCard;
import management.utils.BDConnection;

/**
 * @author Murasov David
 */
public class ReturnBookForm extends javax.swing.JFrame {
    private int studentId, bookId, nrBook;
    private String ISBN;

    public ReturnBookForm() {
        initComponents();
        changeComponents();
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.ORANGE));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/50px-frameIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        issueDateLabel = new javax.swing.JLabel();
        denumireField = new javax.swing.JTextField();
        studentNameField = new javax.swing.JTextField();
        invalidIdLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        bookIdField = new javax.swing.JTextField();
        Label15 = new javax.swing.JLabel();
        Label17 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        ISBNField = new javax.swing.JTextField();
        Label16 = new javax.swing.JLabel();
        findBtn = new rojerusan.RSMaterialButtonCircle();
        returnBtn = new rojerusan.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(122, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(580, 720));

        backLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 153, 0));
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/left-arrow.png"))); // NOI18N
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        jLabel4.setForeground(java.awt.SystemColor.controlHighlight);
        jLabel4.setText("Detalii despre cartea oferită");

        jPanel1.setBackground(java.awt.SystemColor.controlHighlight);
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Label3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label3.setForeground(java.awt.SystemColor.controlHighlight);
        Label3.setText("Denumirea cărtii:");

        Label4.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label4.setForeground(java.awt.SystemColor.controlHighlight);
        Label4.setText("Studentul:");

        Label5.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label5.setForeground(java.awt.SystemColor.controlHighlight);
        Label5.setText("Data oferirii:");

        Label6.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        Label6.setForeground(java.awt.SystemColor.controlHighlight);
        Label6.setText("Termenul:");

        dueDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        dueDateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        dueDateLabel.setForeground(java.awt.SystemColor.controlHighlight);

        issueDateLabel.setBackground(new java.awt.Color(255, 255, 255));
        issueDateLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        issueDateLabel.setForeground(java.awt.SystemColor.controlHighlight);

        denumireField.setBackground(new java.awt.Color(122, 0, 0));
        denumireField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        denumireField.setForeground(java.awt.SystemColor.controlHighlight);
        denumireField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        denumireField.setToolTipText("");
        denumireField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        denumireField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        denumireField.setPreferredSize(new java.awt.Dimension(0, 30));
        denumireField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                denumireFieldMouseClicked(evt);
            }
        });

        studentNameField.setBackground(new java.awt.Color(122, 0, 0));
        studentNameField.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        studentNameField.setForeground(java.awt.SystemColor.controlHighlight);
        studentNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        studentNameField.setToolTipText("");
        studentNameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentNameField.setMargin(new java.awt.Insets(4, 6, 4, 6));
        studentNameField.setPreferredSize(new java.awt.Dimension(0, 30));
        studentNameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentNameFieldMouseClicked(evt);
            }
        });

        invalidIdLabel.setBackground(new java.awt.Color(255, 255, 0));
        invalidIdLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        invalidIdLabel.setForeground(new java.awt.Color(204, 204, 0));
        invalidIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Label5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(denumireField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(studentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(issueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Label6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(invalidIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label3)
                                    .addComponent(denumireField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label4)
                                    .addComponent(studentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(Label5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(issueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(Label6))
                    .addComponent(dueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(invalidIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 77));
        jPanel5.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Returnează cartea");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(115, 115, 115)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel6.setBackground(java.awt.SystemColor.activeCaption);

        bookIdField.setBackground(new java.awt.Color(122, 0, 0));
        bookIdField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bookIdField.setForeground(java.awt.SystemColor.controlHighlight);
        bookIdField.setToolTipText("");
        bookIdField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bookIdField.setMargin(new java.awt.Insets(4, 6, 4, 6));

        Label15.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label15.setText("Id-ul cărtii:");

        Label17.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label17.setText("Id-ul studentului:");

        studentIdField.setBackground(new java.awt.Color(122, 0, 0));
        studentIdField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        studentIdField.setForeground(java.awt.SystemColor.controlHighlight);
        studentIdField.setToolTipText("");
        studentIdField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        studentIdField.setMargin(new java.awt.Insets(4, 6, 4, 6));

        ISBNField.setBackground(new java.awt.Color(122, 0, 0));
        ISBNField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ISBNField.setForeground(java.awt.SystemColor.controlHighlight);
        ISBNField.setToolTipText("");
        ISBNField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        ISBNField.setMargin(new java.awt.Insets(4, 6, 4, 6));

        Label16.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Label16.setText("ISBN al cărtii:");

        findBtn.setBackground(new java.awt.Color(0, 0, 153));
        findBtn.setText("Caută");
        findBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        returnBtn.setBackground(new java.awt.Color(204, 102, 0));
        returnBtn.setText("Returnează");
        returnBtn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label17)
                    .addComponent(Label16)
                    .addComponent(Label15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ISBNField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(studentIdField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookIdField))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(findBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74)
                .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label15)
                    .addComponent(bookIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label16)
                    .addComponent(ISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        redirectTo(new MainPage());
    }//GEN-LAST:event_backLabelMouseClicked

    private void redirectTo(JFrame frame){
        frame.setVisible(true);
        dispose();
    }
    
    public void setBookId(int bookId){
        this.bookId = bookId;
    }
    
    public void setStudentId(int studentId){
        this.studentId = studentId;
    }
    
    public void setNrBook(int nrBook){
        this.nrBook = nrBook;
    }
    
    public void setISBN(String ISBN){
        this.ISBN = ISBN;
    }
    
    private int updateNrBooks(int number){
        int rowCount, nrAfter;
        nrAfter = this.nrBook + number;
        setNrBook(nrAfter);
        
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("UPDATE carti SET nr_carti = ? WHERE id_carte = ?");
            prepst.setInt(1, nrAfter);
            prepst.setInt(2, this.bookId);
            
            return prepst.executeUpdate();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return 0;
    }
    
    public void setInfoIssueBookById(int bookId, int studentId){
    
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("SELECT * FROM carti_oferite cf INNER JOIN carti c ON cf.id_carte = c.id_carte "
                    + "INNER JOIN studenti s ON s.id_studentului = cf.id_studentului WHERE cf.id_carte = ? "
                    + "AND cf.id_studentului = ? AND cf.status = 'In asteptare'");
            
            prepst.setInt(1, bookId);
            prepst.setInt(2, studentId);
            
            ResultSet rs = prepst.executeQuery();
            if(rs.next()){
                setISBN(rs.getString("ISBN"));
                
                denumireField.setText(rs.getString("denumire_carte"));
                studentNameField.setText(rs.getString("numele") + " " + rs.getString("prenumele"));
                issueDateLabel.setText(rs.getString("data_oferirii"));
                dueDateLabel.setText(rs.getString("termenul"));
                invalidIdLabel.setText("");
                returnBtn.setEnabled(true);
            }else{
                denumireField.setText("");
                studentNameField.setText("");
                issueDateLabel.setText("");
                dueDateLabel.setText("");
                
                invalidIdLabel.setText("Nu a fost găsit!");
                returnBtn.setEnabled(false);
            }
            
        }catch(SQLException ex){
            ex.printStackTrace();
        }   
    }
    
    public void setInfoIssueBookByISBN(String ISBN, int studentId){
    try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("SELECT * FROM carti_oferite cf INNER JOIN carti c ON cf.id_carte = c.id_carte "
                    + "INNER JOIN studenti s ON s.id_studentului = cf.id_studentului WHERE c.ISBN = ? "
                    + "AND cf.id_studentului = ? AND cf.status = 'In asteptare'");
            
            prepst.setString(1, ISBN);
            prepst.setInt(2, studentId);
            
            ResultSet rs = prepst.executeQuery();
            if(rs.next()){
                setBookId(Integer.parseInt(rs.getString("id_carte")));
                
                denumireField.setText(rs.getString("denumire_carte"));
                studentNameField.setText(rs.getString("numele") + " " + rs.getString("prenumele"));
                issueDateLabel.setText(rs.getString("data_oferirii"));
                dueDateLabel.setText(rs.getString("termenul"));
                invalidIdLabel.setText("");
                returnBtn.setEnabled(true);
            }else{
                denumireField.setText("");
                studentNameField.setText("");
                issueDateLabel.setText("");
                dueDateLabel.setText("");
                
                invalidIdLabel.setText("Nu a fost găsit!");
                returnBtn.setEnabled(false);
            }
            
        }catch(SQLException ex){
            ex.printStackTrace();
        }  
        
    }
    
    public int returnBook(){
        try(Connection connection = BDConnection.getConnection()){
            PreparedStatement prepst = connection.prepareStatement("UPDATE carti_oferite SET status = 'returnat' WHERE id_carte = ? AND id_studentului = ? AND status = 'In asteptare'");
            
            System.out.println(bookId);
            System.out.println(studentId);
            
            prepst.setInt(1, this.bookId);
            prepst.setInt(2, this.studentId);
            
            return prepst.executeUpdate();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        return 0;
    }
    
    public void setIssuedInfo(Integer bookId, int studentId, String ISBN){
        if(bookId != null){
            setBookId(bookId);
            setInfoIssueBookById(bookId, studentId);
        }else if(!ISBN.equals("")){
            setISBN(ISBN);
            setInfoIssueBookByISBN(ISBN, studentId);
        }else{
            JOptionPane.showMessageDialog(this, "Introduceti id-ul corect sau ISBN");
            return;
        }
    }
    
    
    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        Integer bookId = null, studentId;
        String ISBN;
        
        try{   
            bookId = Integer.parseInt(bookIdField.getText());
        }catch(NumberFormatException e){
            System.out.println(e.getMessage());
        }
        ISBN = ISBNField.getText();
        if(bookId == null && ISBN.equals("")){
           JOptionPane.showMessageDialog(this, "Introduceti id-ul corect sau ISBN");
           return; 
        }
        try{
            studentId = Integer.parseInt(studentIdField.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Introduceti id-ul studentului!");
            return;
        }
        setStudentId(studentId);
        
        setIssuedInfo(bookId, studentId, ISBN);
    }//GEN-LAST:event_findBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        int rowCount = returnBook();
        
        if(rowCount > 0){
            JOptionPane.showMessageDialog(this, "Cartea a fost returnată.");
            rowCount = updateNrBooks(1);
            if(rowCount < 1){
                JOptionPane.showMessageDialog(this, "Eroare de mărire numărului de cărti!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Cartea nu a fost returnată");
        }
    }//GEN-LAST:event_returnBtnActionPerformed

    private void denumireFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denumireFieldMouseClicked
        if(evt.getClickCount() == 2 && evt.getButton() == java.awt.event.MouseEvent.BUTTON1){
            BookInfoCard card = new BookInfoCard();
            card.setValuesToFields(Manages.getBook(bookId));
        }
    }//GEN-LAST:event_denumireFieldMouseClicked

    private void studentNameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentNameFieldMouseClicked
         if(evt.getClickCount() == 2 && evt.getButton() == java.awt.event.MouseEvent.BUTTON1){
             StudentInfoCard card = new StudentInfoCard();
             card.setValuesToFields(Manages.getStudent(studentId));
         }
    }//GEN-LAST:event_studentNameFieldMouseClicked
    
    private void changeComponents(){
        denumireField.setMargin(new Insets(0, 0, 0, 0));
        studentNameField.setMargin(new Insets(0, 0, 0, 0));
        Border empty = new EmptyBorder(0, 0, 0, 0);
        denumireField.setBorder(empty);
        studentNameField.setBorder(empty);
        
        studentNameField.setEditable(false);
        denumireField.setEditable(false);
        
        returnBtn.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNField;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label17;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel backLabel;
    private javax.swing.JTextField bookIdField;
    private javax.swing.JTextField denumireField;
    private javax.swing.JLabel dueDateLabel;
    private rojerusan.RSMaterialButtonCircle findBtn;
    private javax.swing.JLabel invalidIdLabel;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private rojerusan.RSMaterialButtonCircle returnBtn;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTextField studentNameField;
    // End of variables declaration//GEN-END:variables
}
